### PR TITLE
add missing alert types to enum

### LINKED ISSUE #203: Failed to create Datadog::Monitors::Monitor / Type: event-v2 alert
HI, DataDog team.
We're using datadog-cloudformation-resources repo and enjoyed to manage datadog.

Last day we got inform about Datadog::Monitors::Monitor's `event alert` type resource must be update to `event-v2 alert`.
We try to update from CloudFormation, but it failed.

## **Describe the bug**

Create `Datadog::Monitors::Monitor` Type: `event-v2 alert` will be failed.

スクリーンショット 2022-04-22 21 19 44

## **To Reproduce**

Create sample stack and execute
  ```
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  RedisFailoverEventHasOccurred:
    Type: 'Datadog::Monitors::Monitor'
    Properties:
      Type: 'event-v2 alert'
      Query: "events('source:(amazon_elasticache OR Failover)').rollup('count').last('5m') > 0"
      Name: 'failover event has occurred'
      Priority: 4
      Multi: false
      Options:
        Thresholds:
          Critical: 0
          Warning: !Ref AWS::NoValue
          CriticalRecovery: !Ref AWS::NoValue
          WarningRecovery: !Ref AWS::NoValue
        NotifyNoData: false
        EvaluationDelay: 900
      Message: "id: {{event.id}}"
  ``` 

## **Expected reason**

there were no handler for `event-v2 alert` in code.
https://github.com/DataDog/datadog-cloudformation-resources/blob/master/datadog-monitors-monitor-handler/datadog-monitors-monitor.json#L206-L217

## **Environment and Versions (please complete the following information):**

- Datadog Monitor 4.1.0
  - s3://datadog-cloudformation-resources/datadog-monitors-monitor/datadog-monitors-monitor-4.1.0.zip

### PR DESCRIPTION
**Pull request by webratz**
### Requirements for Contributing to this repository

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only fix one issue, or add one feature, at the time.
* The pull request must update the test suite to demonstrate the changed functionality.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see [CONTRIBUTING](/CONTRIBUTING.md).

### What does this PR do?

This fixes #203 
It is adding the allowed alert types as of the library version the custom resources uses (1.8, see https://github.com/DataDog/datadog-api-client-python/blob/1.8.0/src/datadog_api_client/v1/model/monitor_type.py )

This is required as datadog is deprecating the old variant. See also https://docs.datadoghq.com/events/guides/migrating_to_new_events_features/

### Description of the Change

Adding missing alert types to enum to allow to create new event alerts.

### Review checklist (to be filled by reviewers)

- [ ] Feature or bug fix MUST have appropriate tests (unit, integration, etc...)
- [ ] PR title must be written as a CHANGELOG entry [(see why)](/CONTRIBUTING.md#pull-request-title)
- [ ] Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)
- [ ] PR must have one `changelog/` label attached. If applicable it should have the `backward-incompatible` label attached.
- [ ] PR should not have `do-not-merge/` label attached.
- [ ] If Applicable, issue must have `kind/` and `severity/` labels attached at least.

### CODE REVIEW

**Comment by skarimo** [comment]
Thanks for the PR. Could you also add `error-tracking alert` to this pr and run `cfn generate` to generate the new schema and doc changes.

**Comment by webratz** [comment]
I ran the command, guess due to new version it also adjusted the role.
Also updated to the latest python client version, as only this supports the `error-tracking alert`

**Comment by skarimo** [comment]
Thanks for making the changes. We need to release the common package prior to merging this pr. We are planning on releasing and merging this next week.

**Comment by skarimo** [comment]
Superseded by https://github.com/DataDog/datadog-cloudformation-resources/pull/207

**Pull request closed without merging**
