### PR TITLE
Upgrade datadog-cloudformation-common-python version

### PR DESCRIPTION
**Pull request by iwt-dennyschaefer**
### What does this PR do?

This pull request bumps `common-python` to version `0.0.6` in all resources.

When this code has been released, #127 should finally be fixed.

### Review checklist (to be filled by reviewers)

- [ ] Feature or bug fix MUST have appropriate tests (unit, integration, etc...)
- [x] PR title must be written as a CHANGELOG entry [(see why)](/CONTRIBUTING.md#pull-request-title)
- [x] Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)
- [ ] PR must have one `changelog/` label attached. If applicable it should have the `backward-incompatible` label attached.
- [ ] PR should not have `do-not-merge/` label attached.
- [ ] If Applicable, issue must have `kind/` and `severity/` labels attached at least.

### CODE REVIEW

**Comment by tuxinaut** [comment]
The title is a bit misleading now because I can not edit the issue title nor the content anymore.

@zippolyte please have a look, this pull request should be good to go after #146. If you have other plans please let me know and simply close the pull request!

**Review by zippolyte — APPROVED** [review]

**Comment by iwt-dennyschaefer** [comment]
Sorry forgot what I wrote (LAYER 8 problem :facepalm: ) above regarding I'm not able to edit the ticket. I had opened the tab in my private Firefox container instead of the work one .....

**Comment by zippolyte** [comment]
Thanks, I'll release the resources next now that this is merged

**Comment by iwt-dennyschaefer** [comment]
> Thanks, I'll release the resources next now that this is merged

Awesome thx :tada:

**Pull request merged**
