### PR TITLE
Returning normal Physical ID of DataDog Monitor CloudFormation resource

### PR DESCRIPTION
**Pull request by azec-pdx**
### What does this PR do?

This PR addresses [ISSUE 80](https://github.com/DataDog/datadog-cloudformation-resources/issues/80) so that when `DataDog::Monitors::Monitor` CloudFormation resource is stacked, instead of returning (e.g.) `2.0185875E7` as "Pyhsical ID" of resource, it actually returns `20185875` (which can then be used easier in the rest of CloudFormation templates as described in the issue).


### Description of the Change

* Using `string` instead of `number` in `DataDog::Monitors::Monitor` resource JSON schema for `MonitorState.MonitorID.type` property
* Using `string` instead of `number` in `DataDog::Monitors::Monitor` resource JSON schema for `Id` property (id of the Monitor)
* Caused by above two changes and RPDK regenerating new/different model, addressed managing of Monitor IDs in [CreateHandler.java](datadog-monitors-monitor-handler/src/main/java/com/datadog/monitors/monitor/CreateHandler.java), [DeleteHandler.java](datadog-monitors-monitor-handler/src/main/java/com/datadog/monitors/monitor/DeleteHandler.java), [ReadHandler.java](datadog-monitors-monitor-handler/src/main/java/com/datadog/monitors/monitor/ReadHandler.java), [UpdateHandler.java](datadog-monitors-monitor-handler/src/main/java/com/datadog/monitors/monitor/UpdateHandler.java)
* Update on auto-generated docs (by RPDK)
* Changed type of Monitor ID property in [MonitorCRUDTest.java](datadog-monitors-monitor-handler/src/test/java/com/datadog/monitors/monitor/MonitorCRUDTest.java) to make tests functional again after main source changes (described above)


### Alternate Designs

* I have played with alternative of using `integer` as type for two changed JSON properties instead of `string`, but that didn't turn out very well as it imposes conversion from Long to Integers in some places and it could create potential issues for those depending on this as the IDs of monitors on DataDog API side are ever-increasing number. 

### Possible Drawbacks

* Customers who depended on scientific-notation in Physical ID of `DataDog::Monitors::Monitor` (I am in this group) and manipulated it to parse ID of Monitor, will have to change CloudFormation templates to be able to leverage this improvement. But the change is non-breaking for those users, as long as they don't publish new version of Third-Party resource schema (with this fix) to their CloudFormation repository and make it a default one. 

### Verification Process

* Built, tested and packaged with Maven, then packaged with AWS CloudFormation CLI and submitted as new&default version of Third-Party resource to CloudFormation Registry.

```
export DD_TEST_CF_API_KEY='<REDACTED>'
export DD_TEST_CF_APP_KEY='<REDACTED>'
export DD_TEST_CF_API_URL='https://api.datadoghq.com'
mvn test
#...
mvn package
#...
cfn submit \                                                                                                                                                                                                                                       
>     -v \
>     --dry-run \
>     --endpoint-url 'https://cloudformation.us-east-1.amazonaws.com' \
>     --region 'us-east-1' \
>     --set-default \
>     --no-role
Validating your resource specification...
Dry run complete: /Users/azec/dev/datadog-cloudformation-resources/datadog-monitors-monitor-handler/datadog-monitors-monitor.zip
#...
cfn submit \                                                                                                                                                                                                                                               
>     -v \
>     --endpoint-url 'https://cloudformation.us-east-1.amazonaws.com' \
>     --region 'us-east-1' \
>     --set-default \
>     --no-role
Validating your resource specification...
Creating CloudFormationManagedUploadInfrastructure
CloudFormationManagedUploadInfrastructure already exists. Attempting to update
CloudFormationManagedUploadInfrastructure stack is up to date
Successfully submitted type. Waiting for registration with token '<REDACTED>' to complete.
Registration complete.
```
* Verified JUnit tests are passing
<img width="999" alt="Screen Shot 2020-07-28 at 12 15 12 AM" src="https://user-images.githubusercontent.com/1272830/88631760-892f2a80-d067-11ea-8fed-f2c81ce89c0a.png">


* Deployed new CloudFormation template that has several `DataDog::Monitoring::Monitor` resources. Verified that "Physical ID" showed in CloudFormation console IS NOT in scientific notation anymore, but looks like regular number. See screenshot...

<img width="1535" alt="datadog-return-monitor-id-in-non-sci-notation" src="https://user-images.githubusercontent.com/1272830/88627434-2a66b280-d061-11ea-857e-a3b9d4383060.png">

As you can tell there is no anymore `E7` suffix in the values of `Physical ID` of `DataDog::Monitoring::Monitor` resources.


### Additional Notes

* There is a change in `datadog-monitors-monitor-handler/pom.xml` which adds `aws-cloudformation-rpdk-java-plugin` as dependency in this Maven submodule. I am not confident if it is really required, but I was unable to configure my IntelliJ+Maven plugin to build everything without this. I am willing to remove this part if this is just problem that I have (with some guidance on how to configure project without it).

### Release Notes

<!--

If the PR title is not enough to describe the changes in a single line that explains this improvement in
terms that a user can understand. This text will be added in release notes.

For example, you can provide additionnal notes about feature deprecation or backward incompatible changes.

-->

### Review checklist (to be filled by reviewers)

- [x] Feature or bug fix MUST have appropriate tests (unit, integration, etc...)
- [x] PR title must be written as a CHANGELOG entry [(see why)](/CONTRIBUTING.md#pull-request-title)
- [x] Files changes must correspond to the primary purpose of the PR as described in the title (small unrelated changes should have their own PR)
- [x] PR must have one `changelog/` label attached. If applicable it should have the `backward-incompatible` label attached.
- [x] PR should not have `do-not-merge/` label attached.
- [x] If Applicable, issue must have `kind/` and `severity/` labels attached at least.

### CODE REVIEW

**Comment by azec-pdx** [comment]
@bkabrda , I am not sure what/who needs to do PR labeling for it to be officially in the review pipeline, but willing to work through the details together. 
Thank you!

**Comment by azec-pdx** [comment]
Tagging @jirikuncar for visibility...

**Comment by azec-pdx** [comment]
@jirikuncar , thanks for approving that. I am failing to understand what is the failure on the labeler. I don't have experience with this. Any guidance would be helpful, and I am willing to make changes.

Thanks!

**Comment by nmuesch** [comment]
Hey @azec-pdx Sorry for the trouble there, I believe the labeler failure is due to a limitation with forks and can safely be ignored

**Comment by azec-pdx** [comment]
> Hey @azec-pdx Sorry for the trouble there, I believe the labeler failure is due to a limitation with forks and can safely be ignored

Hi @nmuesch , thanks for taking a look? I am wondering if there is any action-items on my end to get that passing. 
I have also reached out to DataDog Slack in [`#integrations`](https://datadoghq.slack.com/archives/C3ZGCF88Z/p1596145569143300) hoping to get some traction with this.

**Comment by nmuesch** [comment]
@azec-pdx I'll go ahead and close this out based on my last notes on the associated issue - https://github.com/DataDog/datadog-cloudformation-resources/issues/80#issuecomment-729845899

**Pull request closed without merging**
